config/routes.rb
Rails.application.routes.draw do
  resources :environments
  # resources :environments, only: :index
  patch  '/environmentsByName'      => 'environmentsapi#updateByName'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/environment.rb
class Environment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def http_basic_authenticate
    authenticate_or_request_with_http_basic do |name, password|
      name == ENV['SECURE_USERNAME'] && password == ENV['SECURE_PASSWORD']
    end
  end

end

app/controllers/environments_controller.rb
class EnvironmentsController < ApplicationController
  before_action :set_environment, only: [:show, :edit, :update, :destroy]

  # GET /environments
  # GET /environments.json
  def index
    @environments = Environment.all.order("id ASC")
  end

  # GET /environments/1
  # GET /environments/1.json
  def show
  end

  # GET /environments/new
  def new
    @environment = Environment.new
  end

  # GET /environments/1/edit
  def edit
  end

  # POST /environments
  # POST /environments.json
  def create
    @environment = Environment.new(environment_params)

    respond_to do |format|
      if @environment.save
        format.html { redirect_to @environment, notice: 'Environment was successfully created.' }
        format.json { render :show, status: :created, location: @environment }
      else
        format.html { render :new }
        format.json { render json: @environment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /environments/1
  # PATCH/PUT /environments/1.json
  def update
    respond_to do |format|
      if @environment.update(environment_params)
        format.html { redirect_to @environment, notice: 'Environment was successfully updated.' }
        format.json { render :show, status: :ok, location: @environment }
      else
        format.html { render :edit }
        format.json { render json: @environment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /environments/1
  # DELETE /environments/1.json
  def destroy
    @environment.destroy
    respond_to do |format|
      format.html { redirect_to environments_url, notice: 'Environment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_environment
      @environment = Environment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def environment_params
      params.require(:environment).permit(:name, :version, :git_hub_release, :url, :db_url, :db_user)
    end
end

app/controllers/environmentsapi_controller.rb
class EnvironmentsapiController < ApplicationController

  protect_from_forgery with: :null_session, if: Proc.new {|c| c.request.format.json? }

  # GET /environments/1
  # GET /environments/1.json
  def show
  end

  # PATCH/PUT /environmentsByName
  # PATCH/PUT /environmentsByName.json
  def updateByName
    
    ENV['WEB_HOOK_KEY'] || raise('no WEB_HOOK_KEY configured')
    
    environment_params
   
    respond_to do |format|
      
      if params["web_hook_key"] != ENV['WEB_HOOK_KEY']
        format.json { render json: {}, status: :unauthorized }
      else
        @environment = Environment.find_by name: params["environment"]["name"]
        if @environment.update(environment_params)
          format.html { redirect_to @environment, notice: 'Environment was successfully updated.' }
          format.json { render :show, status: :ok, location: @environment }
        else
          format.html { render :edit }
          format.json { render json: @environment.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def environment_params
      params.require(:web_hook_key)
      params.require(:environment).permit(:name, :version, :git_hub_release, :url, :db_url, :db_user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/environments_helper.rb
module EnvironmentsHelper
end

app/views/environments/_form.html.erb
<%= form_with(model: environment, local: true) do |form| %>
  <% if environment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(environment.errors.count, "error") %> prohibited this environment from being saved:</h2>

      <ul>
      <% environment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :version %>
    <%= form.text_field :version %>
  </div>

  <div class="field">
    <%= form.label :git_hub_release %>
    <%= form.text_field :git_hub_release %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :db_url %>
    <%= form.text_field :db_url %>
  </div>

  <div class="field">
    <%= form.label :db_user %>
    <%= form.text_field :db_user %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/environments/edit.html.erb
<h1>Editing Environment</h1>

<%= render 'form', environment: @environment %>

<%= link_to 'Show', @environment %> |
<%= link_to 'Back', environments_path %>

app/views/environments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Environments</h1>

<table>
  <thead>
    <tr>
      <th align="left">Name</th>
      <th align="left">Version</th>
      <th/>
<!--      <th>Db url</th>
      <th>Db user</th>-->
    </tr>
  </thead>

  <tbody>
    <% @environments.each do |environment| %>
      <tr>
        <td align="left"><a href="<%= environment.url %>"><%= environment.name %></a></td>
        <td align="left"><%= environment.version %></td> 
        <td>
          <% if environment.git_hub_release.present? %> 
             (<a href="<%= environment.git_hub_release %>">release notes</a>)
          <% end %>
       </td>
<!--        <td><%= environment.db_url %></td>
        <td><%= environment.db_user %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/environments/new.html.erb
<h1>New Environment</h1>

<%= render 'form', environment: @environment %>

<%= link_to 'Back', environments_path %>

app/views/environments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @environment.name %>
</p>

<p>
  <strong>Version:</strong>
  <%= @environment.version %>
</p>

<p>
  <strong>Git hub release:</strong>
  <%= @environment.git_hub_release %>
</p>

<p>
  <strong>Url:</strong>
  <%= @environment.url %>
</p>

<p>
  <strong>Db url:</strong>
  <%= @environment.db_url %>
</p>

<p>
  <strong>Db user:</strong>
  <%= @environment.db_user %>
</p>

<%= link_to 'Edit', edit_environment_path(@environment) %> |
<%= link_to 'Back', environments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Environmentsdashboardapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>